import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Bell, Check, Circle, Clock3, Flame, Focus, GraduationCap, History, LayoutDashboard, ListTodo, Pause, Play, Plus, RotateCcw, Sparkles, TimerReset, CalendarDays} from 'lucide-react';
import {CoreCanvas} from './components/CoreCanvas';
import {useNotifications} from './hooks/useNotifications';
import './styles.css';

const api = async (path, options={}) => { const token=localStorage.getItem('momentum_token'),r=await fetch('/api/'+path,{headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},...options}); if(!r.ok){const body=await r.json().catch(()=>({}));throw new Error(body.error||'Request failed')}return r.status===204?null:r.json(); };
const fmt=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
const quotes=['The quieter you become, the more you can hear.','Small progress is still progress.','Your future is created by what you do today.','Focus is a superpower in a distracted world.','Do the work that makes the future feel possible.','Discipline is choosing what you want most.','A focused hour can change an entire day.','Begin before you feel ready.','Consistency turns intention into momentum.','Protect your attention; it creates your life.','The next right step is enough.','Make room for the work that matters.','Your potential needs a calendar, not just a dream.','Rest is part of the rhythm, not a reward.'];
const dailyQuote=quotes[Math.floor((Date.now()-new Date(new Date().getFullYear(),0,0))/86400000)%quotes.length];
const apkDownloadUrl='/apk';
const seedBlocks=[{id:'a',title:'Deep work · Product design',category:'work',start_time:'09:00',end_time:'10:30',color:'#8b5cf6'},{id:'b',title:'React Three Fiber study',category:'learning',start_time:'11:00',end_time:'12:00',color:'#22d3ee'}];

function App(){
 const [page,setPage]=useState('Dashboard'),[tasks,setTasks]=useState([]),[blocks,setBlocks]=useState([]),[sessions,setSessions]=useState([]),[learning,setLearning]=useState({total_minutes:0,streak:0,milestones:0}),[user,setUser]=useState(null),[authReady,setAuthReady]=useState(false);
 const [mode,setMode]=useState('focus'),[seconds,setSeconds]=useState(30*60),[duration,setDuration]=useState(30),[customHours,setCustomHours]=useState(0),[customMinutes,setCustomMinutes]=useState(30),[running,setRunning]=useState(false),[taskView,setTaskView]=useState('Today');
 const {enabled,request,notify}=useNotifications(); const focused=running&&mode==='focus';
 const refresh=()=>Promise.all([api('tasks'),api('blocks'),api('sessions'),api('learning')]).then(([t,b,s,l])=>{setTasks(t);setBlocks(b.length?b:seedBlocks);setSessions(s);setLearning(l)}).catch(console.error);
 useEffect(()=>{if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(console.error);if(!localStorage.getItem('momentum_token'))return setAuthReady(true);api('auth/me').then(r=>setUser(r.user)).catch(()=>localStorage.removeItem('momentum_token')).finally(()=>setAuthReady(true))},[]);
 useEffect(()=>{if(user)refresh()},[user]);
 useEffect(()=>{if(!running)return; const timer=setInterval(()=>setSeconds(s=>{if(s>1)return s-1;clearInterval(timer);setRunning(false);if(mode==='focus'){api('sessions',{method:'POST',body:JSON.stringify({duration:duration*60,kind:'focus'})}).then(x=>setSessions(v=>[x,...v]));notify('Focus complete','Great work. Take a short, intentional break.',{vibrate:true});setMode('break');return 5*60}notify('Break complete','Your next focus session is ready.',{vibrate:true});setMode('focus');return duration*60}),1000);return()=>clearInterval(timer)},[running,mode,duration,notify]);
 const chooseDuration=m=>{setRunning(false);setMode('focus');setDuration(m);setCustomHours(Math.floor(m/60));setCustomMinutes(m%60);setSeconds(m*60)};
 const applyCustomDuration=()=>{const total=Math.min(1440,Math.max(1,Number(customHours||0)*60+Number(customMinutes||0)));chooseDuration(total)};
 const addTask=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),title=f.get('title')?.trim();if(!title)return;const t=await api('tasks',{method:'POST',body:JSON.stringify({title,priority:f.get('priority'),estimate:Number(f.get('estimate')),status:'today',tags:f.get('tags').split(',').map(x=>x.trim()).filter(Boolean)})});setTasks(x=>[t,...x]);e.currentTarget.reset()};
 const complete=async t=>{const saved=await api('tasks/'+t.id,{method:'PATCH',body:JSON.stringify({status:t.status==='completed'?'today':'completed'})});setTasks(x=>x.map(v=>v.id===t.id?saved:v))};
 const addBlock=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),title=f.get('title')?.trim();if(!title)return;const category=f.get('category'),b=await api('blocks',{method:'POST',body:JSON.stringify({title,category,start_time:f.get('start'),end_time:f.get('end'),color:category==='learning'?'#22d3ee':'#8b5cf6'})});setBlocks(x=>[...x,b].sort((a,b)=>a.start_time.localeCompare(b.start_time)));e.currentTarget.reset()};
 const logStudy=async()=>{const n={...learning,total_minutes:learning.total_minutes+25,streak:Math.max(1,learning.streak)};await api('learning',{method:'PATCH',body:JSON.stringify(n)});setLearning(n)};
 const done=tasks.filter(t=>t.status==='completed'),shown=tasks.filter(t=>taskView==='Completed'?t.status==='completed':taskView==='Backlog'?t.status==='backlog':t.status!=='completed');
 const nav=[['Dashboard',LayoutDashboard],['Focus',Focus],['Planner',CalendarDays],['Tasks',ListTodo],['Learning',GraduationCap],['History',History]];
 if(!authReady)return <main><CoreCanvas active={false}/><div className="auth-loading">Loading Momentum…</div></main>;if(!user)return <AuthGate onSuccess={setUser}/>;return <main><CoreCanvas active={focused}/><div className="app-shell"><header><button className="brand" onClick={()=>setPage('Dashboard')}><span className="brand-mark"><Sparkles size={17}/></span>momentum</button><nav>{nav.map(([name,Icon])=><button key={name} onClick={()=>setPage(name)} className={page===name?'active':''}><Icon size={15}/><span>{name}</span></button>)}</nav><button className="notify" onClick={()=>{localStorage.removeItem('momentum_token');setUser(null)}}>Sign out</button></header>
 {page==='Dashboard'&&<section className="dashboard page"><div className="hero"><div><p className="eyebrow">YOUR DEEP-WORK SPACE</p><h1>Make today <em>matter.</em></h1><p className="muted">Choose one thing. Give it your full attention.</p><div className="hero-actions"><button className="primary" onClick={()=>setPage('Focus')}><Focus size={16}/> Open focus room</button><a className="apk-link" href={apkDownloadUrl}><span>Android</span> Download APK</a></div><small className="apk-note">Install Momentum directly on Android — no Play Store needed.</small></div><div className="quote-card"><img src="/focus-horizon.png" alt="Futuristic horizon for focused work"/><div><span className="eyebrow">DAILY INTENTION</span><blockquote>“{dailyQuote}”</blockquote></div></div></div><div className="overview"><Metric icon={<Check/>} value={done.length} label="tasks completed"/><Metric icon={<Clock3/>} value={`${Math.floor(learning.total_minutes/60)}h`} label="learning time"/><Metric icon={<Flame/>} value={learning.streak} label="day streak"/></div></section>}
 {page==='Focus'&&<section className="focus-page page"><div className="focus-main glass"><span className="eyebrow"><Focus size={14}/> {mode==='focus'?'FOCUS ROOM':'RECOVERY BREAK'}</span><h1>{fmt(seconds)}</h1><p>{mode==='focus'?'One task. One direction. No distractions.':'Stand up, breathe, then return with clarity.'}</p>{mode==='focus'&&<><div className="presets">{[30,45,60].map(m=><button onClick={()=>chooseDuration(m)} className={duration===m?'chosen':''} key={m}>{m} min</button>)}</div><div className="custom-timer"><span>Custom duration</span><label><input aria-label="Hours" value={customHours} onChange={e=>setCustomHours(Math.min(24,Math.max(0,Number(e.target.value))))} type="number" min="0" max="24"/> hours</label><label><input aria-label="Minutes" value={customMinutes} onChange={e=>setCustomMinutes(Math.min(59,Math.max(0,Number(e.target.value))))} type="number" min="0" max="59"/> min</label><button onClick={applyCustomDuration}>Set</button></div></>}<div className="timer-actions"><button className="primary" onClick={()=>{if(!running)notify('Focus session started',`${duration} minute session is now running.`);setRunning(v=>!v)}}>{running?<><Pause size={17}/> Pause</>:<><Play size={17}/> Start session</>}</button><button onClick={()=>{setRunning(false);setSeconds((mode==='focus'?duration:5)*60)}}><RotateCcw size={16}/> Reset</button></div><button className="alert-button" onClick={request}><Bell size={14}/>{enabled?'Alerts enabled':'Enable end-of-session alerts'}</button></div><aside className="glass focus-side"><img src="/focus-horizon.png" alt=""/><div><span className="eyebrow">MOMENTUM NOTE</span><h2>“{dailyQuote}”</h2><p>Completed focus sessions are saved to your history automatically.</p></div></aside></section>}
 {page==='Planner'&&<section className="content-page page"><PageTitle label="UNIFIED TIMETABLE" title="Plan your energy"/><article className="glass planner wide"><form className="block-add" onSubmit={addBlock}><input name="title" placeholder="New block"/><input name="start" type="time" required/><input name="end" type="time" required/><select name="category"><option value="work">Work</option><option value="learning">Learning</option><option value="custom">Custom</option></select><button><Plus size={16}/></button></form><div className="timeline">{blocks.map(b=><div className="block" style={{'--tone':b.color}} key={b.id}><time>{b.start_time}<br/>{b.end_time}</time><div><strong>{b.title}</strong><small>{b.category}</small></div></div>)}</div></article></section>}
 {page==='Tasks'&&<section className="content-page page"><PageTitle label="TASK MANAGER" title="Your next meaningful steps"/><article className="glass wide"><div className="filters">{['Today','Upcoming','Backlog','Completed'].map(x=><button onClick={()=>setTaskView(x)} className={taskView===x?'active':''} key={x}>{x}</button>)}</div><form className="quick-add" onSubmit={addTask}><Plus size={18}/><input name="title" placeholder="Add a task…"/><select name="priority" defaultValue="medium"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select><input name="estimate" type="number" min="5" defaultValue="25"/><input name="tags" placeholder="tags"/><button>Add</button></form><div className="task-list">{shown.length?shown.map(t=><div className="task" key={t.id}><button onClick={()=>complete(t)} className={t.status==='completed'?'done':''}>{t.status==='completed'?<Check size={15}/>:<Circle size={15}/>}</button><div><strong>{t.title}</strong><small><span className={'dot '+t.priority}/>{t.priority} · {t.estimate} min {t.tags?.length?`· ${t.tags.join(', ')}`:''}</small></div></div>):<div className="empty">Nothing here yet. Add a meaningful next step.</div>}</div></article></section>}
 {page==='Learning'&&<section className="content-page page"><PageTitle label="LEARNING LAB" title="Keep the chain alive"/><article className="glass learning wide"><div className="metrics"><Metric icon={<Flame/>} value={learning.streak} label="day streak"/><Metric icon={<TimerReset/>} value={`${Math.floor(learning.total_minutes/60)}h`} label="total learned"/><Metric icon={<Check/>} value={learning.milestones} label="milestones"/></div><button onClick={logStudy} className="primary">Log 25 minutes of learning</button></article></section>}
 {page==='History'&&<section className="content-page page"><PageTitle label="ACTIVITY HISTORY" title="Your effort, recorded"/><div className="history-grid"><article className="glass"><h2>Focus sessions</h2>{sessions.length?sessions.map(s=><div className="history-row" key={s.id}><Focus size={15}/><div><strong>{Math.round(s.duration/60)} minute focus</strong><small>{new Date(s.completed_at).toLocaleString()}</small></div></div>):<div className="empty">Your finished focus sessions will appear here.</div>}</article><article className="glass"><h2>Completed tasks</h2>{done.length?done.map(t=><div className="history-row" key={t.id}><Check size={15}/><div><strong>{t.title}</strong><small>{t.estimate} minutes planned · completed</small></div></div>):<div className="empty">Complete a task to build your record.</div>}</article></div></section>}
 <footer>Designed by <strong>Naveed</strong> · Build your momentum, one focused session at a time.</footer></div></main>}
const Metric=({icon,value,label})=><div className="metric">{icon}<strong>{value}</strong><small>{label}</small></div>;
const PageTitle=({label,title})=><div className="page-title"><span className="eyebrow">{label}</span><h1>{title}</h1></div>;
function AuthGate({onSuccess}){const [register,setRegister]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);const submit=async e=>{e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{const r=await api(`auth/${register?'register':'login'}`,{method:'POST',body:JSON.stringify({email:f.get('email'),password:f.get('password')})});localStorage.setItem('momentum_token',r.token);onSuccess(r.user)}catch(e){setError(e.message)}finally{setBusy(false)}};return <main><CoreCanvas active={false}/><section className="auth-screen"><form className="auth-card glass" onSubmit={submit}><div className="brand"><span className="brand-mark"><Sparkles size={17}/></span>momentum</div><h1>{register?'Create your space':'Welcome back'}</h1><p>{register?'Your tasks, sessions, and learning history stay private to your account.':'Sign in to your private productivity space.'}</p><label>Email<input name="email" type="email" required autoComplete="email" placeholder="you@example.com"/></label><label>Password<input name="password" type="password" required minLength="8" autoComplete={register?'new-password':'current-password'} placeholder="At least 8 characters"/></label>{error&&<div className="auth-error">{error}</div>}<button className="primary" disabled={busy}>{busy?'Please wait…':register?'Create account':'Sign in'}</button><button type="button" className="auth-switch" onClick={()=>{setRegister(v=>!v);setError('')}}>{register?'Already have an account? Sign in':'New here? Create an account'}</button></form></section></main>}
createRoot(document.getElementById('root')).render(<App/>);
