import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Check, Circle, Clock3, Flame, Focus, GraduationCap, ListTodo, Pause, Play, Plus, RotateCcw, Sparkles, TimerReset} from 'lucide-react';
import {CoreCanvas} from './components/CoreCanvas';
import {useNotifications} from './hooks/useNotifications';
import './styles.css';

const api = async (path, options={}) => { const r=await fetch('/api/'+path,{headers:{'Content-Type':'application/json'},...options}); if(!r.ok) throw new Error('Request failed'); return r.status===204?null:r.json(); };
const fmt = s => `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
const seedBlocks=[{title:'Deep work · Product design',category:'work',start_time:'09:00',end_time:'10:30',color:'#8b5cf6'},{title:'React Three Fiber study',category:'learning',start_time:'11:00',end_time:'12:00',color:'#22d3ee'},{title:'Project review',category:'work',start_time:'14:00',end_time:'15:00',color:'#f59e0b'}];

function App(){
 const [tasks,setTasks]=useState([]),[blocks,setBlocks]=useState([]),[learning,setLearning]=useState({total_minutes:0,streak:0,milestones:0});
 const [mode,setMode]=useState('focus'),[seconds,setSeconds]=useState(25*60),[running,setRunning]=useState(false),[tab,setTab]=useState('Today');
 const {enabled,request,notify}=useNotifications(); const focus=running&&mode==='focus';
 useEffect(()=>{ Promise.all([api('tasks'),api('blocks'),api('learning')]).then(([t,b,l])=>{setTasks(t);setBlocks(b.length?b:seedBlocks);setLearning(l)}).catch(console.error) },[]);
 useEffect(()=>{if(!running)return;const id=setInterval(()=>setSeconds(s=>{if(s<=1){clearInterval(id);setRunning(false);const next=mode==='focus'?'break':'focus';setMode(next);const value=next==='focus'?25*60:5*60; notify(next==='focus'?'Focus time':'Break time',next==='focus'?'Your next deep-work block starts now.':'Step away and recharge for five minutes.');return value}return s-1}),1000);return()=>clearInterval(id)},[running,mode,notify]);
 const complete=async task=>{const status=task.status==='completed'?'today':'completed';const saved=await api('tasks/'+task.id,{method:'PATCH',body:JSON.stringify({status})});setTasks(ts=>ts.map(t=>t.id===task.id?saved:t))};
 const addTask=async e=>{e.preventDefault();const form=new FormData(e.currentTarget),title=form.get('title')?.trim();if(!title)return;const task=await api('tasks',{method:'POST',body:JSON.stringify({title,priority:form.get('priority'),estimate:Number(form.get('estimate')),status:'today',tags:form.get('tags').split(',').map(x=>x.trim()).filter(Boolean)})});setTasks(ts=>[task,...ts]);e.currentTarget.reset()};
 const addBlock=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),title=f.get('blockTitle')?.trim();if(!title)return;const block=await api('blocks',{method:'POST',body:JSON.stringify({title,category:f.get('category'),start_time:f.get('start'),end_time:f.get('end'),color:f.get('category')==='learning'?'#22d3ee':'#8b5cf6'})});setBlocks(bs=>[...bs,block].sort((a,b)=>a.start_time.localeCompare(b.start_time)));e.currentTarget.reset()};
 const visible=tasks.filter(t=>tab==='Completed'?t.status==='completed':tab==='Backlog'?t.status==='backlog':t.status!=='completed');
 const start=()=>{ if(!running) notify(mode==='focus'?'Focus session started':'Break started',mode==='focus'?'Momentum is tracking your deep work.':'Time to reset.'); setRunning(v=>!v) };
 const logStudy=async()=>{const next={...learning,total_minutes:learning.total_minutes+25,streak:Math.max(1,learning.streak)};await api('learning',{method:'PATCH',body:JSON.stringify(next)});setLearning(next)};
 return <main><CoreCanvas active={focus}/><div className="shell">
  <header><div className="brand"><span className="brand-mark"><Sparkles size={18}/></span><span>momentum</span></div><nav>{['Today','Upcoming','Backlog','Completed'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav><button className="notify" onClick={request}>{enabled?'Alerts on':'Enable alerts'}</button></header>
  <section className="hero"><div><p className="eyebrow">MONDAY · SEPTEMBER 14</p><h1>Make today <em>matter.</em></h1><p className="muted">A quiet space for your most important work.</p></div><div className="daily"><span>Daily momentum</span><strong>{Math.min(100,Math.round((tasks.filter(t=>t.status==='completed').length/Math.max(tasks.length,1))*100))}%</strong><div className="progress"><i style={{width:`${Math.min(100,Math.round((tasks.filter(t=>t.status==='completed').length/Math.max(tasks.length,1))*100))}%`}}/></div></div></section>
  <section className="grid"><div className="stack">
   <article className="glass timer"><div className="card-label"><span><Focus size={16}/> {mode==='focus'?'FOCUS SESSION':'RECOVERY BREAK'}</span><button onClick={()=>{setRunning(false);setSeconds(mode==='focus'?1500:300)}}><RotateCcw size={16}/></button></div><div className="time">{fmt(seconds)}</div><p>{mode==='focus'?'Protect your attention. One thing at a time.':'A little pause clears the way for better work.'}</p><div className="timer-actions"><button className="primary" onClick={start}>{running?<><Pause size={17}/> Pause</>:<><Play size={17}/> Start focus</>}</button><button onClick={()=>{setRunning(false);setMode(mode==='focus'?'break':'focus');setSeconds(mode==='focus'?300:1500)}}>Switch mode</button></div></article>
   <article className="glass tasks"><div className="section-head"><div><span className="card-label">YOUR TASKS</span><h2>{tab}</h2></div><span className="count">{visible.length}</span></div><form className="quick-add" onSubmit={addTask}><Plus size={18}/><input name="title" placeholder="Add a task…"/><select name="priority" defaultValue="medium"><option value="low">Low</option><option value="medium">Med</option><option value="high">High</option></select><input name="estimate" type="number" min="5" defaultValue="25"/><input name="tags" placeholder="tags"/><button>Add</button></form><div className="task-list">{visible.length?visible.map(t=><div className="task" key={t.id}><button onClick={()=>complete(t)} className={t.status==='completed'?'done':''}>{t.status==='completed'?<Check size={15}/>:<Circle size={15}/>}</button><div><strong>{t.title}</strong><small><span className={'dot '+t.priority}/>{t.priority} · {t.estimate} min {t.tags?.length?`· ${t.tags.join(', ')}`:''}</small></div></div>):<div className="empty">Your list is clear. Add one meaningful next step.</div>}</div></article>
  </div>
  <div className="stack"><article className="glass planner"><div className="section-head"><div><span className="card-label">UNIFIED TIMETABLE</span><h2>Today's flow</h2></div><Clock3 size={19}/></div><form className="block-add" onSubmit={addBlock}><input name="blockTitle" placeholder="New block"/><input name="start" type="time" required/><input name="end" type="time" required/><select name="category"><option value="work">Work</option><option value="learning">Learning</option><option value="custom">Custom</option></select><button><Plus size={15}/></button></form><div className="timeline">{blocks.map(b=><div className="block" style={{'--tone':b.color}} key={b.id}><time>{b.start_time}<br/>{b.end_time}</time><div><strong>{b.title}</strong><small>{b.category === 'learning'?'Study / Learning':b.category==='work'?'Work':b.category}</small></div></div>)}</div></article>
   <article className="glass learning"><div className="section-head"><div><span className="card-label">LEARNING LAB</span><h2>Keep the chain alive</h2></div><GraduationCap size={20}/></div><div className="metrics"><div><Flame/><strong>{learning.streak}</strong><small>day streak</small></div><div><TimerReset/><strong>{Math.floor(learning.total_minutes/60)}h</strong><small>total learned</small></div><div><Check/><strong>{learning.milestones}</strong><small>milestones</small></div></div><button onClick={logStudy} className="secondary">Log 25 min learning</button></article>
  </div></section>
 </div></main>
}
createRoot(document.getElementById('root')).render(<App/>);
